### ISSUE TITLE
Makefile:25: recipe for target 'minialloc.o' failed

### ISSUE THREAD

**Issue by Romainpkq** [bicici/FDA#1]
When I run "make" command in gcc version 7.5.0, I have the error mentioned in the title. Does anyone knows how to solve this problem?

The detail error:
g++ -c -O3 -D_XOPEN_SOURCE -Wall -I. 'pkg-config --cflags glib-2.0' minialloc.c -o minialloc.o
minialloc.c:6:17: error: 'void* free' redeclared as different kind of symbol
 static gpointer free;
                 ^~~~
In file included from /usr/include/c++/7/cstdlib:75:0,
                 from /usr/include/c++/7/stdlib.h:36,
                 from /usr/include/glib-2.0/glib/gutils.h:306,
                 from /usr/include/glib-2.0/glib/gthread.h:34,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from minialloc.c:1:
/usr/include/stdlib.h:563:13: note: previous declaration 'void free(void*)'
 extern void free (void *__ptr) __THROW;
             ^~~~
minialloc.c: In function 'void newdata(gpointer)':
minialloc.c:12:17: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
     free = data + sizeof(gpointer);
            ~~~~~^~~~~~~~~
minialloc.c:12:34: error: assignment of function 'void free(void*)'
     free = data + sizeof(gpointer);
                                  ^
minialloc.c:12:34: error: cannot convert 'gpointer {aka void*}' to 'void(void*) throw ()' in assignment
minialloc.c: In function 'void* minialloc(gsize)':
minialloc.c:21:19: error: invalid conversion from 'void (*)(void*) throw ()' to 'gpointer {aka void*}' [-fpermissive]
   gpointer rval = free;
                           ^~~~
minialloc.c:22:8: warning: pointer to a function used in arithmetic [-Wpointer-arith]
         free += size;
    ~~~~~^~~~~~~
minialloc.c:22:11: error: assignment of read-only location 'free'
   free += size;
                ^~~~
minialloc.c:22:11: error: cannot convert 'void (*)(void*) throw ()' to 'void(void*) throw ()' in assignment
Makefile:25: recipe for target 'minialloc.o' failed
make: *** [minialloc.o] Error 1

**Comment by bicici** [comment]
Try renaming free to another variable name such as free2 in minialloc.c and make compiles with gcc 8.3.0.

Also note that this is likely to be a compiler issue. You can also retry with gcc 6 if gcc 7 gave you this error.
